apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gophprofile.fullname" . }}-worker
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "gophprofile.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gophprofile.workerSelectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "gophprofile.serviceAccountName" . }}
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.worker.command | nindent 12 }}
          ports:
            - name: metrics
              containerPort: 8081
              protocol: TCP
          env:
            - name: WORKER_METRICS_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ include "gophprofile.fullname" . }}-config
                  key: WORKER_METRICS_ADDR
            {{- include "gophprofile.commonEnv" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
