apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.fullname" . }}-server
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "gophprofile.serverSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.fullname" . }}-worker-metrics
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: {{ .Values.workerMetricsService.type }}
  ports:
    - name: metrics
      port: {{ .Values.workerMetricsService.port }}
      targetPort: {{ .Values.workerMetricsService.targetPort }}
      protocol: TCP
  selector:
    {{- include "gophprofile.workerSelectorLabels" . | nindent 4 }}
